### ISSUE TITLE
[object Object] error when trying to enter figma url

### ISSUE THREAD

**Issue by ghost** [impress-dev/support#3]
Hi,

Im trying to setup the flow from figma to impress to wappler, but on the first hurdle I get met with a '[object Object]' error when trying to enter your 'Kitchen SInk' url (or any other) for figma.

<img width="796" alt="Screenshot 2024-10-14 at 14 20 18" src="https://github.com/user-attachments/assets/d721b896-b899-413d-ba95-770b5a8e77ff">

**Comment by ghost** [comment]
it seems to have disappeared for now. Im wondering was it due to the fact that i didn't click the link in an email to authorise my account? Im not sure if i didn't click it in the first place, i just know i clicked it again and it disappeared.

**Comment by impress-dev** [comment]
Thanks for reporting this. I've made some improvements to the error messaging, so should this happen again then hopefully a better error message will present itself.

**Comment by impress-dev** [comment]
Fix implemented and released to production.
